PACKAGE_NAME="book4-edge-anatase"
PACKAGE_VERSION="1.1"
AUTOINSTALL="yes"

MAKE[0]="make KDIR=${kernel_source_dir} -C ${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build"

BUILT_MODULE_NAME[0]="ene-kb9058-battery"
DEST_MODULE_LOCATION[0]="/kernel/drivers/power/supply"

BUILT_MODULE_NAME[1]="samsung-emuec"
DEST_MODULE_LOCATION[1]="/kernel/drivers/usb/typec"
